spring:
  application:
    name: acquisition
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://192.168.1.4:8083/auth/realms/smartfactory
          jwkSetUri: http://192.168.1.4:8083/auth/realms/smartfactory/protocol/openid-connect/certs
  data:
    mongodb:
      database: acquisition
      host: 192.168.1.4
      port: 27017
  rabbitmq:
    host: 192.168.1.4
    port: 5672
    username: admin
    password: admin
server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@192.168.1.4:8761/eureka
mqtt:
  publisher-id: spring-server
  server: tcp://192.168.1.4:1883
smartfactory:
  rabbitmq:
    exchange: exchange.mqtt
    queue: queue.mqtt
    routingkey: routingkey.mqtt
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always