spring:
  application:
    name: acquisition
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: ${KEYCLOAK_URL}/auth/realms/master
          jwkSetUri: ${KEYCLOAK_URL}/auth/realms/master/protocol/openid-connect/certs
  data:
    mongodb:
      uri: ${MONGODB_URI}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
server:
  port: 8002
mqtt:
  publisher-id: spring-server
  server: tcp://${MQTT_HOST}:${MQTT_PORT}
smartfactory:
  rabbitmq:
    mqtt:
      exchange: mqtt_events
      subscription:
        queue: mqtt_subscription_queue
      gateway:
        queue: mqtt_gateway_queue
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always