spring:
  application:
    name: acquisition
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://192.168.49.2:8083/auth/realms/smartfactory
          jwkSetUri: http://192.168.49.2:8083/auth/realms/smartfactory/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
  data:
    mongodb:
      uri: mongodb://root:8yegPnqjzd@192.168.49.6:27017/acquisition?authSource=admin
  rabbitmq:
    host: 192.168.49.5
    port: 5672
    username: admin
    password: admin
server:
  port: 8002
mqtt:
  publisher-id: spring-server
  server: tcp://192.168.49.7:1883
smartfactory:
  rabbitmq:
    mqtt:
      exchange: mqtt_events
      subscription:
        queue: mqtt_subscription_queue
      gateway:
        queue: mqtt_gateway_queue
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always