spring:
  application:
    name: acquisition-data-mqtt-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://192.168.1.5:8083/auth/realms/baeldung
          jwkSetUri: http://192.168.1.5:8083/auth/realms/baeldung/protocol/openid-connect/certs
  data:
    mongodb:
      database: smartfactory
      host: 192.168.1.5
      port: 27017
server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@192.168.1.5:8761/eureka
mqtt:
  publisher-id: spring-server
  server: tcp://192.168.1.5:1883
